### PR TITLE
Add `plot(..)` to `Display`

### PR DESCRIPTION
**Pull request by Otard95**
### Goal
This PR aims to implement the plotting functionality provided by the external script shared by @dbuezas in their [comment](https://github.com/yunabe/tslab/issues/46#issuecomment-792366727) on #46.

It adds the `plot()` function to the `Display` interface and implementation in `DisplayImpl`.
https://github.com/yunabe/tslab/blob/f056a88baf81a1fc6a01b0446a3febcf919ff8e4/src/public.ts#L20
https://github.com/yunabe/tslab/blob/f056a88baf81a1fc6a01b0446a3febcf919ff8e4/src/public.ts#L45

### Licence
As @dbuezas only provided the js as is, with no licence, I feel we should get their permission to use the script in this way.

### Disclaimer
I've not worked on a JupyterLab extension before, but as far as i can tell this runs on the backend so using the cdn is required. This also makes getting typed arguments difficult as plotly.js naturally need the `window` and `document` globals.

### CODE REVIEW

**Comment by dbuezas** [comment]
I'm honoured :) permission granted. Thanks to the authors & contribuitors of this kernel btw.

There's some hacky denouncing in place to deal with a vscode specific issue when more than 1 plots are shown in the same block. I'm currently about to move so short in time this month, but I'll happily try to help if asked to. I'll try to post the version I'm currently using tomorrow in case you prefer that one (api a bit cleaner)

**Comment by Otard95** [comment]
Plotly.js is provided under the [MIT](https://github.com/plotly/plotly.js/blob/master/LICENSE) licence so it should be just fine.

**Comment by yunabe** [comment]
> Plotly.js is provided under the MIT licence

Why is the license of plotly.js matters here? Did you copy the code from plotly.js? If so, we have to include their license in our repository and it's not acceptable naively.

If the code was written by you and we just load plotly.js from their CDN, the license does not matter a lot.

**Comment by Otard95** [comment]
> Did you copy the code from plotly.js?

No, i did not.

> If the code was written by you and we just load plotly.js from their CDN, the license does not matter at all IMHO.

I feel the same.

**Pull request merged**
